name: CI
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        electron: [7.1.2, 9.0.0, 10.2.0, 11.4.10, 12.0.0]
        app: ['primary', secondary]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        env:
          ELECTRON_VERSION: ${{ matrix.electron }}
        run: |
          cd ${{ matrix.app }} && yarn update-electron && yarn install

      - name: Install the Apple certificate
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Build artifacts
        env:
          BUILD_NUMBER: ${{ github.run_number	 }}
          ELECTRON_VERSION: ${{ matrix.electron }}
        run: |
          cd ${{ matrix.app }} && yarn build:testing

      - name: Clean up keychain
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db

      - uses: actions/upload-artifact@v2
        with:
          name: rdc-${{ matrix.app }}-electron-${{ matrix.electron }}-${{ runner.os }}
          path: |
            primary/dist/*.dmg
            primary/dist/*.exe
            secondary/dist/*.dmg
            secondary/dist/*.exe

      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            primary/dist/*.dmg
            primary/dist/*.exe
            secondary/dist/*.dmg
            secondary/dist/*.exe
