name: CI
on: [push, release]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: cd primary && yarn install && cd ../ && cd secondary && yarn install && cd ../

      - name: Install the Apple certificate
        if: ${{ matrix.os == 'macos-latest' }}
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      - name: Build artifacts
        env:
          BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER	 }}
        run: cd primary && yarn build:testing && cd ../ && cd secondary && yarn build:testing && cd ../

      - name: Clean up keychain
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db

      - uses: actions/upload-artifact@v2
        with:
          name: rdc-artifacts-${{ github.runner_os }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/**/dist/*.dmg
            ${{ github.workspace }}/**/dist/*.exe

      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            **/*.dmg
            **/*.exe
